<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Application\GarageFlow.Serverless.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.100.13" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>
</Project>
